### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.

In [1]:
sexo = 'M'
beta_hcg = 0

# seu código vem abaixo desta linha

sexo = input('Insira o sexo "M ou F": ')

if sexo == 'M':
    print('Parabéns, gostando ou não, você é do sexo masculino.')
elif sexo == 'm':
    print('Parabéns, gostando ou não, você é do sexo masculino.')
    
elif sexo == 'f':
    beta_hcg = int(input('Qual a quantidade de beta-HCG no seu sangue?: '))
    if beta_hcg > 5:
        print('POSITIVO! Parabéns futura mamãe, você vai ter que parar de beber whiskey por um tempo.')

    elif beta_hcg <= 5:
        print('NEGATIVO! Não foi dessa vez, pode voltar para festa.')
    
elif sexo == 'F':
    beta_hcg = int(input('Qual a quantidade de beta-HCG no seu sangue?: '))
    if beta_hcg > 5:
        print('POSITIVO! Parabéns futura mamãe, você vai ter que parar de beber whiskey por um tempo.')

    else:
        print('NEGATIVO! Não foi dessa vez, pode voltar para festa.')


Insira o sexo "M ou F": m
Parabéns, gostando ou não, você é do sexo masculino.


### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.

In [2]:
dic_renomeacao = {'name': 'nome', 'age': 'idade', 'income': 'renda'}
dic_renomeacao

{'name': 'nome', 'age': 'idade', 'income': 'renda'}

### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.

In [110]:
N = 42
M = 7

#Seu código

for M in range(7,N):
    if( N % M == 0 or M % N == 0):
        print(M, "É divisível")
 


    





7 É divisível
14 É divisível
21 É divisível


### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.

In [109]:
N = 47


# seu código abaixo

for i in range(1,N-1):
    if (N % i) == 0:
        print(N, "É um número primo")


47 É um número primo


### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.

In [ ]:
N = 98

# seu código aqui



### 06 - Peso ideal 1
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

$$ IMC = \dfrac{peso}{altura^2}$$

Segundo a OMS, valores *normais* são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.

In [43]:
imc_ideal = (18.5 + 24.9) / 2
imc_ideal

21.7

### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima

In [44]:
altura = 1.70

# Seu código
peso_ideal = 21.7 * (altura ** 2)
peso_ideal

62.712999999999994

### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.

In [48]:
lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código

import numpy as np

lista_alturas = np.array([1.95, 2.05, 1.70, 1.65])
lista_alturas * lista_alturas * 21.7





array([82.51425, 91.19425, 62.713  , 59.07825])

### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.

In [11]:
altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código

altura_peso = np.array([(1.80, 90), (1.65, 75), (1.91, 70)])
altura_peso




array([[ 1.8 , 90.  ],
       [ 1.65, 75.  ],
       [ 1.91, 70.  ]])

In [12]:
altura_peso[:,1]/(altura_peso[:,0]**2)

array([27.77777778, 27.54820937, 19.1880705 ])

### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

In [14]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

# seu código

for num in altura_peso:
    valor = round((num[1] / num[0]**2), 2)
    
    if valor < 18.5:
        imc = 'Você está magro. Coma mais, por favor.'
    elif valor > 24.9:
        imc = 'Por favor, coma menos, faça exercícios, você está acima do peso.'
    else:
        imc = 'Parabéns, você está dentro da média que a OMS estipulou. Reze para ela ter razão :)'

    num.append(valor)
    num.append(imc)

altura_peso

[[1.8,
  90,
  27.78,
  'Por favor, coma menos, faça exercícios, você está acima do peso.'],
 [1.65,
  75,
  27.55,
  'Por favor, coma menos, faça exercícios, você está acima do peso.'],
 [1.91,
  70,
  19.19,
  'Parabéns, você está dentro da média que a OMS estipulou. Reze para ela ter razão :)']]